server:
  servlet:
    context-path: /
  port: 8081
springdoc:
  api-docs:
    path: /
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  redis:
    client-name: master
    password: fpt@123456
    url: redis://localhost:6379
  data:
    rest:
      base-path: /api
  datasource:
    driver-class-name: org.postgresql.Driver
    password: fpt@123456
    url: jdbc:postgresql://localhost:5000/quiz-api-db
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
token:
  jwt:
    secret-key: 3618bf61-a667-4139-ac23-4267323e6217
    expiration-time: 300000
cloudinary:
  cloud-name: fpt-software-quiz
  api-key: 446252591291621
  api-secret: w6AQxknBfDg_ykT_NKFlTOOxQsw
