server:
  servlet:
    context-path: /
  port: 8081
springdoc:
  api-docs:
    path: /
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  redis:
    client-name: master
    password: fpt@123456
    url: redis://localhost:6379
  data:
    elasticsearch:
      elastic-password: fpt@123456
    rest:
      base-path: /api
  datasource:
    driver-class-name: org.postgresql.Driver
    password: fpt@123456
    url: jdbc:postgresql://localhost:5432/quiz-api-db
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    oauth2:
      client:
        redirectUrl: http://localhost:8080/quizsystem_war/auth/oauth2
        registration:
          google:
            clientId: 1011455872750-lnsck8sej8rbj7o39bohbotek1mpb7dp.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile
logging:
  level:
    org:
      springframework:
        data:
          elasticsearch:
            client:
              WIRE: TRACE
token:
  jwt:
    secret-key: 3618bf61-a667-4139-ac23-4267323e6217
    expiration-time: 300000
cloudinary:
  cloud-name: fpt-software-quiz
  api-key: 446252591291621
  api-secret: w6AQxknBfDg_ykT_NKFlTOOxQsw
