version: '3.9'
volumes:
  db-data:
    name: postgres-db-volume
  cache-data:
    name: redis-volume
services:
  db:
    image: postgres
    restart: always
    ports:
      - "5000:5432"
    env_file:
      - database.env
    volumes:
      - db-data:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      # copy the sql script to fill tables
      - ./sql/fill_tables.sql:/docker-entrypoint-initdb.d/fill_tables.sql
  adminer:
    image: adminer
    restart: always
    ports:
      - "5001:8080"
  cache:
    image: redis
    restart: always
    command: redis-server --requirepass fpt@123456
    ports:
      - "5002:6379"
    environment:
      - REDIS_RELICATION_MODE=master
    volumes:
      - cache-data:/data